### ISSUE TITLE
Can't shuffle the library: TypeError: __init__() missing 1 required positional argument: 'artistId

### ISSUE THREAD

**Issue by blastbeng** [srichter/asksonic#10]
Hi,
this error started showing up yesterday, when i say "alexa, tell sub sonic to shuffle my library" 

```
9:22:45 AM web.1 |  Traceback (most recent call last):
9:22:45 AM web.1 |    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
9:22:45 AM web.1 |      response = self.full_dispatch_request()
9:22:45 AM web.1 |    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
9:22:45 AM web.1 |      rv = self.handle_user_exception(e)
9:22:45 AM web.1 |    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
9:22:45 AM web.1 |      rv = self.dispatch_request()
9:22:45 AM web.1 |    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
9:22:45 AM web.1 |      return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
9:22:45 AM web.1 |    File "/usr/local/lib/python3.9/site-packages/flask_ask/core.py", line 890, in _flask_view_func
9:22:45 AM web.1 |      result = self._map_intent_to_view_func(self.request.intent)()
9:22:45 AM web.1 |    File "/app/asksonic/intents/navigation.py", line 25, in play_random_tracks
9:22:45 AM web.1 |      tracks = subsonic.random_tracks(tracks_count)
9:22:45 AM web.1 |    File "/app/asksonic/utils/subsonic/api.py", line 83, in random_tracks
9:22:45 AM web.1 |      tracks = [Track(**track) for track in tracks]
9:22:45 AM web.1 |    File "/app/asksonic/utils/subsonic/api.py", line 83, in <listcomp>
9:22:45 AM web.1 |      tracks = [Track(**track) for track in tracks]
9:22:45 AM web.1 |  TypeError: __init__() missing 1 required positional argument: 'artistId'
```

Initially it was working, i've changed nothing since some days ago and now i can't shuffle my library anymore

What's the problem? May be something wrong with Navidrome?

Yes i use Navidrome as music server, it has 1.16.1 subsonic api

**Comment by srichter** [comment]
This is a bug introduced by a recent Navidrome update. I'll push a fix shortly.

**Comment by srichter** [comment]
Fixed in c38f229edaf4c801a14c07b5ada3ae0a7928ef8c

**Comment by blastbeng** [comment]
Thanks, looks like it is working now!

**Comment by blastbeng** [comment]
By the way I'm also a developer, if you need any help by introducing new features in this awesome alexa tool you can contact me on Discors @blastbeng#9151

**Comment by srichter** [comment]
> By the way I'm also a developer, if you need any help by introducing new features in this awesome alexa tool you can contact me on Discord @blastbeng#9151

Awesome! If you'd like, feel free to pick up any of the open issues, or add your own feature you think would be useful.
